# Generated by Django 3.1.7 on 2021-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
