# Generated by Django 3.1.7 on 2021-05-08 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0002_busstand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='schedules_id',
        ),
        migrations.AddField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 8, 4, 41, 23, 342795, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 8, 4, 41, 23, 342795, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tickets',
            name='route_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BusTracking.routes'),
        ),
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
