# Generated by Django 3.1.7 on 2021-05-08 04:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0003_auto_20210508_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='bus_id',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='pass_id',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='route_id',
            new_name='routes',
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 8, 4, 44, 9, 932873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 8, 4, 44, 9, 932873, tzinfo=utc)),
        ),
    ]
