# Generated by Django 3.1.7 on 2021-05-10 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0007_auto_20210508_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='cost',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='tripDate',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 10, 12, 27, 7, 607808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 10, 12, 27, 7, 607808, tzinfo=utc)),
        ),
    ]
