# Generated by Django 3.1.7 on 2021-05-10 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0008_auto_20210510_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstand',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BusTracking.bus'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 10, 14, 18, 10, 354101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 10, 14, 18, 10, 354101, tzinfo=utc)),
        ),
    ]
