# Generated by Django 3.1.7 on 2021-05-11 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0010_auto_20210511_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 11, 6, 4, 35, 841309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 11, 6, 4, 35, 841309, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='BookMultipleRoutesTickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('routes', models.CharField(max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusTracking.passenger')),
            ],
        ),
    ]
