# Generated by Django 3.1.7 on 2021-05-12 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0013_auto_20210511_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(default='BusTracking/images/image1.webp', upload_to=''),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='tripDate',
            field=models.DateField(default=datetime.date(2021, 5, 12)),
        ),
        migrations.AlterField(
            model_name='query',
            name='QueryDate',
            field=models.DateField(default=datetime.date(2021, 5, 12)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 12, 12, 21, 35, 690619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 12, 12, 21, 35, 690619, tzinfo=utc)),
        ),
    ]
