# Generated by Django 3.1.7 on 2021-05-15 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0014_auto_20210512_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tripDate', models.DateField(default=datetime.date(2021, 5, 15))),
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='age',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='tripDate',
        ),
        migrations.AddField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 15)),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email_id',
            field=models.IntegerField(default='raunak@321', max_length=40),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone_no',
            field=models.IntegerField(default=9351951340, max_length=20),
        ),
        migrations.AlterField(
            model_name='query',
            name='QueryDate',
            field=models.DateField(default=datetime.date(2021, 5, 15)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 4, 31, 45, 63661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 4, 31, 45, 63661, tzinfo=utc)),
        ),
    ]
