# Generated by Django 3.1.7 on 2021-05-15 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0015_auto_20210515_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='email_id',
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_no',
            field=models.IntegerField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 4, 33, 4, 446923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 4, 33, 4, 446923, tzinfo=utc)),
        ),
    ]
