# Generated by Django 3.1.7 on 2021-05-15 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0030_auto_20210515_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdate',
            old_name='id',
            new_name='trip_id',
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 4, 50, 18, 182390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 4, 50, 18, 182390, tzinfo=utc)),
        ),
    ]
