# Generated by Django 3.1.7 on 2021-05-15 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0041_auto_20210515_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDate',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('tripDate', models.DateField(default=datetime.date(2021, 5, 15))),
            ],
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='tripDate',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 5, 10, 17, 486076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 15, 5, 10, 17, 486076, tzinfo=utc)),
        ),
    ]
