# Generated by Django 3.1.7 on 2021-05-16 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0048_auto_20210515_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BusTracking.tripdate'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
        migrations.AlterField(
            model_name='query',
            name='QueryDate',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 16, 12, 0, 11, 690018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 16, 12, 0, 11, 690018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripdate',
            name='tripDate',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
    ]
