# Generated by Django 3.1.7 on 2021-05-17 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0049_auto_20210516_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='QueryDate',
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 17, 11, 40, 49, 696409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 17, 11, 40, 49, 696409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripdate',
            name='tripDate',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
    ]
