# Generated by Django 3.1.7 on 2021-05-17 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0050_auto_20210517_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='QueryDate',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 17, 11, 44, 26, 101206, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 17, 11, 44, 26, 101206, tzinfo=utc)),
        ),
    ]
