# Generated by Django 3.1.7 on 2021-05-20 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0051_auto_20210517_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmultipleroutestickets',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BusTracking.tripdate'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 20)),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 20)),
        ),
        migrations.AlterField(
            model_name='query',
            name='QueryDate',
            field=models.DateField(default=datetime.date(2021, 5, 20)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 20, 6, 7, 8, 103690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 20, 6, 7, 8, 103690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tripdate',
            name='tripDate',
            field=models.DateField(default=datetime.date(2021, 5, 20)),
        ),
    ]
