# Generated by Django 3.1.7 on 2021-05-20 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0052_auto_20210520_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmultipleroutestickets',
            name='cost',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='bookmultipleroutestickets',
            name='routeDestination',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='DRoutes', to='BusTracking.routes'),
        ),
        migrations.AddField(
            model_name='bookmultipleroutestickets',
            name='routeOrigin',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ORoutes', to='BusTracking.routes'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 20, 9, 19, 49, 119673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 20, 9, 19, 49, 119673, tzinfo=utc)),
        ),
    ]
