# Generated by Django 3.1.7 on 2021-05-23 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0059_auto_20210523_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 5, 2, 34, 441242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 5, 2, 34, 441242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seats',
            name='tripdate',
            field=models.DateField(default=datetime.date(2021, 5, 23)),
        ),
    ]
