# Generated by Django 3.1.7 on 2021-05-23 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BusTracking', '0060_auto_20210523_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='bus_id',
        ),
        migrations.AlterField(
            model_name='routes',
            name='destinationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 5, 27, 28, 16531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stationTime',
            field=models.TimeField(default=datetime.datetime(2021, 5, 23, 5, 27, 28, 16531, tzinfo=utc)),
        ),
    ]
